- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - puppet-openstack-integration-5-scenario001-tempest-ubuntu-bionic-mimic:
            voting: false
        - puppet-openstack-integration-5-scenario001-tempest-centos-7-luminous:
            voting: false
        - puppet-openstack-integration-5-scenario004-tempest-ubuntu-bionic-mimic:
            voting: false
        - puppet-openstack-integration-5-scenario004-tempest-centos-7-mimic:
            voting: false
